"""Alembic environment — the migration wrapper (RFC-002 §9, RFC-001 §13).

Every migration connection is opened as the BYPASSRLS ``migrator`` role and immediately
constrained by:
  - ``lock_timeout = '2s'``       — never wait long for a lock (fail fast, retry later)
  - ``statement_timeout = '30s'`` — no runaway DDL

CREATE INDEX CONCURRENTLY must run outside a transaction; use ``op.get_context()
.autocommit_block()`` in those revisions. The migration lint (scripts/check_migrations.py)
enforces CONCURRENTLY on tables above the 1M-row threshold.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, text

from relay.db_metadata import target_metadata
from relay.settings import get_settings

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()

# Alembic uses the sync psycopg DSN for the BYPASSRLS migrator role.
MIGRATION_URL = settings.migration_database_url

LOCK_TIMEOUT = "2s"
STATEMENT_TIMEOUT = "30s"


def _apply_timeouts(connection: object) -> None:
    connection.execute(text(f"SET lock_timeout = '{LOCK_TIMEOUT}'"))  # type: ignore[attr-defined]
    connection.execute(text(f"SET statement_timeout = '{STATEMENT_TIMEOUT}'"))  # type: ignore[attr-defined]


def run_migrations_offline() -> None:
    context.configure(
        url=MIGRATION_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(MIGRATION_URL, future=True)
    with engine.connect() as connection:
        _apply_timeouts(connection)
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            # Keep autogenerated names deterministic via the naming convention on Base.
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
